package com.example.model

object CourtData {
    val districts: List<String> = listOf(
        "Adilabad",
        "Bhadradri Kothagudem",
        "Hanumakonda / Warangal",
        "Hyderabad",
        "Jagtial",
        "Jangaon",
        "Jayashankar Bhupalpally",
        "Jogulamba Gadwal",
        "Kamareddy",
        "Karimnagar",
        "Khammam",
        "Komaram Bheem Asifabad",
        "Mahabubabad",
        "Mahabubnagar",
        "Mancherial",
        "Medak",
        "Medchal-Malkajgiri",
        "Mulugu",
        "Nagarkurnool",
        "Nalgonda",
        "Narayanpet",
        "Nirmal",
        "Nizamabad",
        "Peddapalli",
        "Rajanna Sircilla",
        "Rangareddy (L.B. Nagar)",
        "Sangareddy",
        "Siddipet",
        "Suryapet",
        "Vikarabad",
        "Wanaparthy",
        "Yadadri Bhuvanagiri"
    ).sorted()

    val telanganaCourts: Map<String, List<String>> = mapOf(
        "Adilabad" to listOf(
            "IN THE COURT OF THE HON’BLE FASTRACK SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF CASES UNDER SC/ST (POA) ACT, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE CUM ASSISTANT SESSIONS JUDGE, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ADILABAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: UTNOOR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: BOATH"
        ),
        "Hyderabad" to listOf(
            "IN THE COURT OF THE HON’BLE METROPOLITAN SESSIONS JUDGE, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE CHIEF METROPOLITAN MAGISTRATE, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL CHIEF METROPOLITAN MAGISTRATE, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF SPE & ACB CASES, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SPECIAL JUDGE FOR CBI CASES, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR POCSO CASES, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR TRIAL OF SC/ST (POA) ACT CASES, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE I SPECIAL METROPOLITAN MAGISTRATE, AT: HYDERABAD",
            "IN THE COURT OF THE HON’BLE II SPECIAL METROPOLITAN MAGISTRATE, AT: HYDERABAD"
        ),
        "Rangareddy (L.B. Nagar)" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: L.B. NAGAR, RANGAREDDY",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: L.B. NAGAR, RANGAREDDY",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: L.B. NAGAR, RANGAREDDY",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR TRIAL OF SC/ST (POA) ACT CASES, AT: L.B. NAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR TRIAL OF CYBER CRIME CASES, AT: L.B. NAGAR",
            "IN THE COURT OF THE HON’BLE METROPOLITAN MAGISTRATE, AT: CYBERABAD (L.B. NAGAR)",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: RAJENDRANAGAR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MAHESWARAM",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: IBRAHIMPATNAM",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SHADNAGAR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: CHEVELLA"
        ),
        "Medchal-Malkajgiri" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MEDCHAL-MALKAJGIRI",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: MEDCHAL-MALKAJGIRI",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: MEDCHAL-MALKAJGIRI",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF SC/ST ACT CASES, AT: MEDCHAL-MALKAJGIRI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE CUM ASSISTANT SESSIONS JUDGE, AT: MEDCHAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE CUM ASSISTANT SESSIONS JUDGE, AT: MALKAJGIRI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE CUM ASSISTANT SESSIONS JUDGE, AT: KUKATPALLY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM IX METROPOLITAN MAGISTRATE, AT: KUKATPALLY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM METROPOLITAN MAGISTRATE, AT: MEDCHAL"
        ),
        "Hanumakonda / Warangal" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: HANUMAKONDA",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: HANUMAKONDA",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: HANUMAKONDA",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR SC/ST (POA) ACT CASES, AT: HANUMAKONDA",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR SPE & ACB CASES, AT: WARANGAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: WARANGAL",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL SENIOR CIVIL JUDGE, AT: WARANGAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL MAGISTRATE OF FIRST CLASS, AT: WARANGAL",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL MAGISTRATE OF FIRST CLASS, AT: NARSAMPET",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL MAGISTRATE OF FIRST CLASS, AT: PARKAL"
        ),
        "Karimnagar" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR TRIAL OF SC/ST (POA) ACT CASES, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR SPE & ACB CASES, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KARIMNAGAR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: HUZURABAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: CHOPPADANDI",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MANTHANI"
        ),
        "Khammam" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR TRIAL OF SC/ST (POA) ACT CASES, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KHAMMAM",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SATHUPALLY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MADHIRA"
        ),
        "Nalgonda" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR SC/ST (POA) ACT CASES, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: NALGONDA",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: MIRYALAGUDA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MIRYALAGUDA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: DEVARKONDA"
        ),
        "Nizamabad" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR SC/ST (POA) ACT CASES, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: NIZAMABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: BODHAN",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: ARMOOR"
        ),
        "Mahabubnagar" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE SPECIAL SESSIONS JUDGE FOR SC/ST ACT CASES, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MAHABUBNAGAR",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: JADCHERLA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SHADNAGAR"
        ),
        "Bhadradri Kothagudem" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: KOTHAGUDEM",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: KOTHAGUDEM",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: KOTHAGUDEM",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: KOTHAGUDEM",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KOTHAGUDEM",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: YELLANDU",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: BHADRACHALAM",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MANUGURU"
        ),
        "Jagtial" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: JAGTIAL",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: JAGTIAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: JAGTIAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: JAGTIAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: METPALLY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KORUTLA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: DHARMAPURI"
        ),
        "Jangaon" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: JANGAON",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: JANGAON",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: JANGAON"
        ),
        "Jayashankar Bhupalpally" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: BHUPALPALLY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: BHUPALPALLY",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: BHUPALPALLY"
        ),
        "Jogulamba Gadwal" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: GADWAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: GADWAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: GADWAL",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ALAMPUR"
        ),
        "Kamareddy" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: KAMAREDDY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: KAMAREDDY",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KAMAREDDY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: YELLAREDDY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: BANSWADA"
        ),
        "Komaram Bheem Asifabad" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: ASIFABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: ASIFABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ASIFABAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SIRPUR (T)"
        ),
        "Mahabubabad" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MAHABUBABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: MAHABUBABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MAHABUBABAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: THORRUR"
        ),
        "Mancherial" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MANCHERIAL",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: MANCHERIAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: MANCHERIAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MANCHERIAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: BELLAMPALLY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: CHENNUR"
        ),
        "Medak" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MEDAK",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: MEDAK",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MEDAK",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: NARSAPUR"
        ),
        "Mulugu" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: MULUGU",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: MULUGU",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MULUGU"
        ),
        "Nagarkurnool" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: NAGARKURNOOL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: NAGARKURNOOL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: NAGARKURNOOL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: KALWAKURTHY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: ACHAMPET",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KOLLAPUR"
        ),
        "Narayanpet" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: NARAYANPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: NARAYANPET",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: NARAYANPET",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MAKTHAL"
        ),
        "Nirmal" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: NIRMAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: NIRMAL",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: NIRMAL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: BHAINSA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KHANAPUR"
        ),
        "Peddapalli" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: PEDDAPALLI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: PEDDAPALLI",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: PEDDAPALLI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: GODAVARIKHANI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: SULTANABAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: MANTHANI"
        ),
        "Rajanna Sircilla" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: SIRCILLA",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: SIRCILLA",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SIRCILLA",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: VEMULAWADA"
        ),
        "Sangareddy" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: SANGAREDDY",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: SANGAREDDY",
            "IN THE COURT OF THE HON’BLE SPECIAL JUDGE FOR TRIAL OF POCSO CASES, AT: SANGAREDDY",
            "IN THE COURT OF THE HON’BLE PRINCIPAL SENIOR CIVIL JUDGE, AT: SANGAREDDY",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SANGAREDDY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: ZAHEERABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: ANDOLE-JOGIPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: NARAYANKHED"
        ),
        "Siddipet" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: SIDDIPET",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: SIDDIPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: SIDDIPET",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SIDDIPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: GAJWEL",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: DUBBAK",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: HUSNABAD"
        ),
        "Suryapet" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: SURYAPET",
            "IN THE COURT OF THE HON’BLE I ADDITIONAL DISTRICT AND SESSIONS JUDGE, AT: SURYAPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: SURYAPET",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: SURYAPET",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: HUZURNAGAR",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: KODAD",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: THUNGATHURTHY"
        ),
        "Vikarabad" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: VIKARABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: VIKARABAD",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: VIKARABAD",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: TANDUR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: PARGI",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: KODANGAL"
        ),
        "Wanaparthy" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: WANAPARTHY",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: WANAPARTHY",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: WANAPARTHY",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ATMAKUR"
        ),
        "Yadadri Bhuvanagiri" to listOf(
            "IN THE COURT OF THE HON’BLE PRINCIPAL DISTRICT AND SESSIONS JUDGE, AT: BHUVANAGIRI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: BHUVANAGIRI",
            "IN THE COURT OF THE HON’BLE PRINCIPAL JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: BHUVANAGIRI",
            "IN THE COURT OF THE HON’BLE SENIOR CIVIL JUDGE, AT: RAMANNAPET",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: ALAIR",
            "IN THE COURT OF THE HON’BLE JUNIOR CIVIL JUDGE CUM JUDICIAL FIRST CLASS MAGISTRATE, AT: CHOUTUPPAL"
        )
    )

    val commonReasons: List<String> = listOf(
        "suffering from ill health",
        "suffering from viral fever and chest pain",
        "undergoing medical treatment and advised bed rest",
        "urgent family medical emergency",
        "unable to travel due to severe illness",
        "stuck due to public transport disruption / breakdown",
        "hospitalized and undergoing diagnosis"
    )

    val commonPurposes: List<String> = listOf(
        "his appearance and for Examination",
        "appearance and framing of charges",
        "appearance and Section 313 examination",
        "appearance and cross-examination of witnesses",
        "appearance and arguments",
        "hearing and appearance"
    )
}
